name: .NET

on:
  push:
   tags:
   - v*.*.*
   branches:
   - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}   
    - name: Get the version2
      id: get_version2
      run: echo ::debug::${GITHUB_REF#refs/tags/v} 
    - name: Get the version3
      id: get_version3
      run: echo ::debug::${{ steps.get_version.outputs.VERSION }} 
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: AwaitableWaitHandle/AwaitableWaitHandle.csproj
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        VERSION_STATIC: ${{ steps.get_version.outputs.VERSION }}
